# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'selfhelp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
#   rn_path = '../node_modules/react-native'
#   pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
#   pod 'React', path: rn_path, subspecs: [
#   'Core',
#   'RCTActionSheet',
#   'RCTAnimation',
#   'RCTGeolocation',
#   'RCTImage',
#   'RCTLinkingIOS',
#   'RCTNetwork',
#   'RCTSettings',
#   'RCTText',
#   'RCTVibration',
#   'RCTWebSocket'
#   ]

    pod 'TwilioVoice', '~> 2.0.0'
    # pod 'RNTwilioVoice', :path => '../node_modules/react-native-twilio-programmable-voice'
  # Pods for selfhelp

end

# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
# post_install do |installer|
#     installer.pods_project.targets.each do |target|
#         if target.name == "React"
#             target.remove_from_project
#         end
#     end
# end
